### ISSUE TITLE
Overlapping activities

### ISSUE THREAD

**Issue by artur-borowiec** [DroidsOnRoids/Toast-App#150]
After clicking 'Prelegenci' and 'Kontakt' buttons simultaneously few times, contact activity overlaps the other one.

![28945885_1720745607972212_2124929781_o](https://user-images.githubusercontent.com/23338187/37797663-bbf20f10-2e1a-11e8-81fc-1d02904719e9.png)
![29390850_1720745604638879_226418227_o](https://user-images.githubusercontent.com/23338187/37797664-bc3f36a0-2e1a-11e8-809d-eb111478f8ff.png)

**Comment by Nonda95** [comment]
Fixed in #154
